import { chromium } from 'playwright-core';
import { fileURLToPath } from 'node:url';
const out = fileURLToPath(new URL('../out/', import.meta.url));
const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport:{width:900,height:1400}, deviceScaleFactor:2.4 });
await p.goto('file://' + out + process.argv[2], { waitUntil:'networkidle' });
await p.evaluate(()=>document.fonts.ready); await p.waitForTimeout(400);
await p.screenshot({ path: out + process.argv[3], fullPage:true });
console.log('→', process.argv[3]);
await b.close();
